### 自動對數據進行分析產生報表

In [17]:
import numpy as np
import pandas as pd
from ydata_profiling import ProfileReport

# 創建隨機數據
df = pd.read_csv(r'C:\Users\yifun\Desktop\python_code\train.csv')

# 生成分析報告
profile = ProfileReport(df, title="Titanic Report")

# 將報告輸出為HTML文件
profile.to_file("Titanic_report.html")


Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

c:\Users\yifun\anaconda3\lib\site-packages\ydata_profiling\model\typeset_relations.py:117: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  return pd.to_datetime(series)
c:\Users\yifun\anaconda3\lib\site-packages\ydata_profiling\model\typeset_relations.py:117: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  return pd.to_datetime(series)
c:\Users\yifun\anaconda3\lib\site-packages\ydata_profiling\model\typeset_relations.py:117: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  return pd.to_datetime(series)
c:\Users\yifun\anaconda3\lib\site-packages\ydata_profiling\model\typeset_relati

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

# 數值型資料前處理

### 正規化(Min-Max Scaling)

In [27]:
from tensorflow.keras.datasets import mnist

(X_train,y_train),(X_test,y_test) = mnist.load_data()

print(X_train[0][5])  # 輸出第0張圖的第5列

[  0   0   0   0   0   0   0   0   0   0   0   0   3  18  18  18 126 136
 175  26 166 255 247 127   0   0   0   0]


In [28]:
# 進行正規化
(X_train / 255.0 )[0][5]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.01176471, 0.07058824, 0.07058824,
       0.07058824, 0.49411765, 0.53333333, 0.68627451, 0.10196078,
       0.65098039, 1.        , 0.96862745, 0.49803922, 0.        ,
       0.        , 0.        , 0.        ])

In [29]:
# 進行標準化
X_mean = X_train.mean()
X_std = np.std(X_train)

((X_train - X_mean) / X_std)[0][5]

array([-0.42407389, -0.42407389, -0.42407389, -0.42407389, -0.42407389,
       -0.42407389, -0.42407389, -0.42407389, -0.42407389, -0.42407389,
       -0.42407389, -0.42407389, -0.38589016, -0.1949715 , -0.1949715 ,
       -0.1949715 ,  1.17964286,  1.30692197,  1.80331049, -0.09314822,
        1.68875929,  2.82154335,  2.71972006,  1.19237077, -0.42407389,
       -0.42407389, -0.42407389, -0.42407389])

In [ ]:
# 使用對數轉換來趨近於常態分佈
import numpy as np
x = ([1.0,10.0,100.0,1000.0,10000.0])

np.log1p(x)  # 使用log(x+1)來求出對數

array([0.69314718, 2.39789527, 4.61512052, 6.90875478, 9.21044037])

# 類別型資料前處理

### 1. Label Encoding

In [23]:
from sklearn.preprocessing import LabelEncoder

data = ['A1','A2','A3','A4','B5','B6','B1','A8','A9']

le = LabelEncoder()  # 建立LabelEncoder
le.fit(data)         # 將其初始化
print(le.classes_)   # 查看標籤類別
print(le.transform(data))

['A1' 'A2' 'A3' 'A4' 'A8' 'A9' 'B1' 'B5' 'B6']
[0 1 2 3 7 8 6 4 5]


### 2. One-hot encoding

In [ ]:
# 對數值執行one-hot encoding
from sklearn.preprocessing import OneHotEncoder

df = np.array([0,1,2,3,4,5,6,7,8,9])
ohe = OneHotEncoder(sparse=False)
print(ohe.fit_transform(df.reshape(-1,1)))

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


C:\Users\yifun\AppData\Roaming\Python\Python38\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [36]:
# 對文字執行one-hot encoding
data = np.array(['A1','A2','A3','A4','B5','B6','B1','A8','A9'])

ohe = OneHotEncoder(sparse=False)
print(ohe.fit_transform(data.reshape(-1,1)))

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]]


C:\Users\yifun\AppData\Roaming\Python\Python38\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


# 文字資料的預處理

### Bag-of-words: 以單詞為單位進行分割

In [39]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?'
]

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(corpus)
print(X.toarray())

print(vectorizer.vocabulary_)

[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]
{'this': 8, 'is': 3, 'the': 6, 'first': 2, 'document': 1, 'second': 5, 'and': 0, 'third': 7, 'one': 4}


### N-gram: 以連續詞組為單位進行分割

In [40]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?'
]

vectorizer = CountVectorizer(analyzer='word', ngram_range=(2,2))

X = vectorizer.fit_transform(corpus)
print(X.toarray())

print(vectorizer.vocabulary_)

[[0 0 1 1 0 0 1 0 0 0 0 1 0]
 [0 1 0 1 0 1 0 1 0 0 1 0 0]
 [1 0 0 1 0 0 0 0 1 1 0 1 0]
 [0 0 1 0 1 0 1 0 0 0 0 0 1]]
{'this is': 11, 'is the': 3, 'the first': 6, 'first document': 2, 'this document': 10, 'document is': 1, 'the second': 7, 'second document': 5, 'and this': 0, 'the third': 8, 'third one': 9, 'is this': 4, 'this the': 12}


### TF-IDF: 將資料轉換成一個文本n*字詞的出現次數k的矩陣 (多考慮了單詞的重要程度)

In [41]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?'
]

vectorizer = CountVectorizer()
transformer = TfidfTransformer()

tf = vectorizer.fit_transform(corpus)
tfidf = transformer.fit_transform(tf)

tfidf.toarray()

array([[0.        , 0.46979139, 0.58028582, 0.38408524, 0.        ,
        0.        , 0.38408524, 0.        , 0.38408524],
       [0.        , 0.6876236 , 0.        , 0.28108867, 0.        ,
        0.53864762, 0.28108867, 0.        , 0.28108867],
       [0.51184851, 0.        , 0.        , 0.26710379, 0.51184851,
        0.        , 0.26710379, 0.51184851, 0.26710379],
       [0.        , 0.46979139, 0.58028582, 0.38408524, 0.        ,
        0.        , 0.38408524, 0.        , 0.38408524]])

### Embedding: 將單詞or類別變數 轉換為實數向量的方法

In [45]:
from gensim.models import Word2Vec

corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?'
]

sentence = [i.split() for i in corpus]

model = Word2Vec(sentence, window=2, min_count=1, workers=4)

print(model.wv['This'])  # 把This轉換為向量
print(model.wv['is']) # 把is轉換為向量

[-8.7274825e-03  2.1301615e-03 -8.7354420e-04 -9.3190884e-03
 -9.4281426e-03 -1.4107180e-03  4.4324086e-03  3.7040710e-03
 -6.4986930e-03 -6.8730675e-03 -4.9994122e-03 -2.2868442e-03
 -7.2502876e-03 -9.6033178e-03 -2.7436293e-03 -8.3628409e-03
 -6.0388758e-03 -5.6709289e-03 -2.3441375e-03 -1.7069972e-03
 -8.9569986e-03 -7.3519943e-04  8.1525063e-03  7.6904297e-03
 -7.2061159e-03 -3.6668312e-03  3.1185520e-03 -9.5707225e-03
  1.4764392e-03  6.5244664e-03  5.7464195e-03 -8.7630618e-03
 -4.5171441e-03 -8.1401607e-03  4.5956374e-05  9.2636338e-03
  5.9733056e-03  5.0673080e-03  5.0610625e-03 -3.2429171e-03
  9.5521836e-03 -7.3564244e-03 -7.2703874e-03 -2.2653891e-03
 -7.7856064e-04 -3.2161034e-03 -5.9258583e-04  7.4888230e-03
 -6.9751858e-04 -1.6249407e-03  2.7443992e-03 -8.3591007e-03
  7.8558037e-03  8.5361041e-03 -9.5840869e-03  2.4462664e-03
  9.9049713e-03 -7.6658037e-03 -6.9669187e-03 -7.7365171e-03
  8.3959233e-03 -6.8133592e-04  9.1444086e-03 -8.1582209e-03
  3.7430846e-03  2.63504

In [ ]:
model.wv.most_similar('document')  # 找出與document最相似的詞

[('first', 0.15016479790210724),
 ('And', 0.12813477218151093),
 ('the', 0.0931011214852333),
 ('this', 0.04652618244290352),
 ('document?', 0.0007268059416674078),
 ('is', -0.0036444426514208317),
 ('document.', -0.009253410622477531),
 ('second', -0.03030233457684517),
 ('one.', -0.04044133797287941),
 ('Is', -0.040919121354818344)]